
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 04 14:56:07 BRT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 22;
  public static final int SIGNED = 23;
  public static final int FECHACOCHETES = 65;
  public static final int LEFT_ASSIGN = 36;
  public static final int IDENTIFIER = 81;
  public static final int MOD_ASSIGN = 41;
  public static final int OR_OP = 51;
  public static final int BARRA = 73;
  public static final int DOISPONTOS = 60;
  public static final int SUB_ASSIGN = 38;
  public static final int AND_OP = 50;
  public static final int CONST = 6;
  public static final int TIO = 69;
  public static final int VIRGULA = 59;
  public static final int REGISTER = 20;
  public static final int ENUM = 12;
  public static final int SIZEOF = 24;
  public static final int INC_OP = 47;
  public static final int GE_OP = 53;
  public static final int DEC_OP = 48;
  public static final int AND_ASSIGN = 42;
  public static final int DOUBLE = 10;
  public static final int STRUCT = 26;
  public static final int LE_OP = 52;
  public static final int MAIORQUE = 76;
  public static final int INTERROGACAO = 79;
  public static final int XOR_ASSIGN = 43;
  public static final int MENORQUE = 75;
  public static final int FLOAT = 14;
  public static final int GOTO = 16;
  public static final int ABREPARENTESES = 62;
  public static final int RIGHT_ASSIGN = 35;
  public static final int PIPELINE = 78;
  public static final int ADD_ASSIGN = 37;
  public static final int LONG = 19;
  public static final int IGUAL = 61;
  public static final int PONTO = 66;
  public static final int WHILE = 33;
  public static final int UNION = 29;
  public static final int MUL_ASSIGN = 39;
  public static final int CHAR = 5;
  public static final int ASTERISCO = 72;
  public static final int ABRECHAVES = 57;
  public static final int PTR_OP = 49;
  public static final int SWITCH = 27;
  public static final int DO = 9;
  public static final int FOR = 15;
  public static final int VOID = 31;
  public static final int EXTERN = 13;
  public static final int RETURN = 21;
  public static final int ELSE = 11;
  public static final int MENOS = 70;
  public static final int BREAK = 3;
  public static final int PONTOEVIRGULA = 56;
  public static final int INT = 18;
  public static final int STRING_LITERAL = 82;
  public static final int EOF = 0;
  public static final int DEFAULT = 8;
  public static final int MAIS = 71;
  public static final int EXCLAMACAO = 68;
  public static final int CONSTANT = 80;
  public static final int CIRCUNFLEXO = 77;
  public static final int PORCENTO = 74;
  public static final int error = 1;
  public static final int RIGHT_OP = 45;
  public static final int OR_ASSIGN = 44;
  public static final int CONTINUE = 7;
  public static final int IF = 17;
  public static final int UNSIGNED = 30;
  public static final int DIV_ASSIGN = 40;
  public static final int FECHAPARENTESES = 63;
  public static final int ECOMERCIAL = 67;
  public static final int FECHACHAVES = 58;
  public static final int ABRECOCHETES = 64;
  public static final int VOLATILE = 32;
  public static final int NE_OP = 55;
  public static final int CASE = 4;
  public static final int EQ_OP = 54;
  public static final int ELLIPSIS = 34;
  public static final int STATIC = 25;
  public static final int TYPEDEF = 28;
  public static final int AUTO = 2;
  public static final int LEFT_OP = 46;
}

