
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 02 21:14:44 BRT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int NUMBER = 8;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int TIMES = 7;
  public static final int LPAREN = 2;
}

